version: '3'
services:
  airflowproject:
    image: airflow-project:latest
    secrets:
      - access_key
      - access
      - api_key
    environment:
      - AWS_ACCESS_KEY_ID=/run/env/access_key.txt
      - AWS_SECRET_ACCESS_KEY=/run/env/access.txt
      - YOUTUBE_API_KEY= /run/env/api_key.txt
    volumes:
      - ./youtube_trend_analysis:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone